/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import Image from 'next/image';
import tw, { styled, theme, css } from 'twin.macro';
import { keyframes } from 'styled-components';
import OrderSummary from '../components/OrderSummary';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main tw='relative min-h-screen grid place-items-center bg-primary-paleBlue'>
        <img src='/images/pattern-background-desktop.svg' alt='' tw='hidden xl:block z-10 absolute top-0 right-0 w-full left-0 object-cover ' />
        <OrderSummary />
      </main>
    </div>
  );
}
