/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import Image from 'next/image';
import tw, { styled, theme, css } from 'twin.macro';
import { keyframes } from 'styled-components';
import Breadcrumb from '../components/Breadcrumb';
import { useState } from 'react';

export default function Home() {
  const [crumbs, setCrumbs] = useState(['Home', 'Category', 'Sub Category']);

  const selected = (crumb) => {
    console.log(crumb);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Breadcrumb crumbs={crumbs} selected={selected} />
    </div>
  );
}
